package dk.itu.datasys;

import dk.itu.datasys.sql.CopyStatement;
import dk.itu.datasys.sql.CreateTableStatement;
import dk.itu.datasys.sql.Predicate;
import dk.itu.datasys.sql.SelectStatement;
import dk.itu.datasys.sql.Statement;
import dk.itu.datasys.storage.ColumnSpec;
import dk.itu.datasys.storage.ColumnType;
import dk.itu.datasys.storage.Comparison;

import java.util.List;
import java.util.Optional;
import java.util.stream.Stream;

import org.junit.jupiter.api.Test;
import org.junit.jupiter.params.ParameterizedTest;
import org.junit.jupiter.params.provider.Arguments;
import org.junit.jupiter.params.provider.MethodSource;

import static org.junit.jupiter.api.Assertions.assertEquals;
import static org.junit.jupiter.api.Assertions.assertThrows;

class SqlParserTest {

    private final SqlParser parser = new SqlParser();

    @Test
    void eachStatementShapeParsesToExpectedAst() {
        assertEquals(
                new CreateTableStatement("trips", List.of(
                        new ColumnSpec("city", ColumnType.STRING),
                        new ColumnSpec("distance", ColumnType.LONG),
                        new ColumnSpec("price", ColumnType.DOUBLE))),
                parseOne("CREATE TABLE trips (city STRING, distance LONG, price DOUBLE);"));
        assertEquals(
                new CopyStatement("trips", "trips.csv"),
                parseOne("COPY trips FROM 'trips.csv';"));
        assertEquals(
                new SelectStatement("trips", Optional.of(
                        new Predicate("distance", Comparison.GREATER_THAN, 100L))),
                parseOne("SELECT * FROM trips WHERE distance > 100;"));
        assertEquals(
                new SelectStatement("trips", Optional.empty()),
                parseOne("SELECT * FROM trips;"));
    }

    @Test
    void literalsAreTypedAndNegativesParse() {
        assertEquals(12L, constantOf("SELECT * FROM trips WHERE distance = 12;"));
        assertEquals(12.0, constantOf("SELECT * FROM trips WHERE price = 12.0;"));
        assertEquals("12", constantOf("SELECT * FROM trips WHERE city = '12';"));
        assertEquals(-1L, constantOf("SELECT * FROM trips WHERE distance = -1;"));
        assertEquals(-1.5, constantOf("SELECT * FROM trips WHERE price = -1.5;"));
    }

    @Test
    void integerOverflowReportsLineAndColumn() {
        // Long.MAX_VALUE is 9223372036854775807; one more overflows.
        String sql = "SELECT * FROM trips WHERE distance = 9223372036854775808;";
        SqlParseException error = assertThrows(SqlParseException.class, () -> parser.parse(sql));
        assertEquals(1, error.line());
        assertEquals("SELECT * FROM trips WHERE distance = ".length(), error.column());
    }

    @Test
    void keywordsAreCaseInsensitiveAndIdentifierCasingIsPreserved() {
        assertEquals(
                new SelectStatement("trips", Optional.empty()),
                parseOne("select * from trips;"));
        assertEquals(
                new SelectStatement("Trips", Optional.empty()),
                parseOne("SELECT * FROM Trips;"));
    }

    // this test is parameterized to test the parser with different malformed inputs
    // the inputs are generated by the malformedInputs() method below (stream of 5 arg-sets)
    @ParameterizedTest(name = "{0}")
    @MethodSource("malformedInputs")
    void malformedInputReportsLineAndColumn(String name, String sql, int line, int column) {
        SqlParseException error = assertThrows(SqlParseException.class, () -> parser.parse(sql));
        assertEquals(line, error.line());
        assertEquals(column, error.column());
    }

    static Stream<Arguments> malformedInputs() {
        return Stream.of(
                Arguments.of("missing semicolon", "SELECT * FROM trips", 1, 19),
                Arguments.of("unbalanced parens", "CREATE TABLE trips (city STRING;", 1, 31),
                Arguments.of("unknown type name", "CREATE TABLE trips (city TEXT);", 1, 25),
                Arguments.of("unterminated string", "COPY trips FROM 'trips.csv;", 1, 16),
                Arguments.of("missing FROM", "SELECT * trips;", 1, 9));
    }

    @Test
    void commentsAndWhitespaceAreSkipped() {
        String messy = """
                -- leading comment
                SELECT   *
                FROM\ttrips  -- trailing comment
                WHERE   distance   >   100;
                """;
        assertEquals(parseOne("SELECT * FROM trips WHERE distance > 100;"), parseOne(messy));
    }

    private Statement parseOne(String sql) {
        List<Statement> statements = parser.parse(sql);
        assertEquals(1, statements.size());
        return statements.getFirst();
    }

    private Object constantOf(String sql) {
        SelectStatement select = (SelectStatement) parseOne(sql);
        return select.where().orElseThrow().constant();
    }
}
